package momo.jdbc.memo;

public class Memo {
	
	private long id;   	    //메모일련번호(PK)
	private String content;	//메모내용
			
	public Memo(long id, String content) {
		super();
		this.id = id;
		this.content = content;
	}
	
	//set(), get(), toString()
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Override
	public String toString() {
		return "Memo [id=" + id + ", content=" + content + "]";
	}
	
}
/*
CREATE TABLE memo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    
    content VARCHAR2(1000)
);
*/